### PR TITLE
 Added a Frontend of basic wallet and generation of public key and pr…

### PR DESCRIPTION
**Pull request by Shashwat8038**
…i have made a simple wallet frontend and generated public key and private key for every transaction

### CODE REVIEW

**Comment by kartik739** [comment]
bro how come all the lines from all files same as the solution given by chatgpt ? just asking mate

**Comment by devsargam** [comment]
`node_modules` 💀

**Comment by TanmayDhobale** [comment]
> `node_modules` 💀

haha

**Comment by us3r64bit** [comment]
> bro how come all the lines from all files same as the solution given by chatgpt ? just asking mate

it's claude. :slightly_smiling_face:

**Comment by rohitt-gupta** [comment]
> `node_modules` 💀

Merge it, PR looks good.

**Comment by kartik739** [comment]
> > bro how come all the lines from all files same as the solution given by chatgpt ? just asking mate
> 
> it's claude. 🙂

still the same thing

**Review by Rudra-Sankha-Sinhamahapatra — COMMENTED** [review]
please delete the node modules

**Comment by hkirat** [comment]
This isn't a race. Make the PR slowly, review your code 10 times.
Google the comments above and try fixing what's being mentioned
Closing for now

**Comment by Shashwat8038** [comment]
Hey there It wasn't chatGpt.. I wrote all by my self but I had to clear an
error of npm run minor so I had used chatGpt to resolve that error and fix
the code ...Not everything that shines is chatGpt.(mate)..just saying ..

**Comment by Shashwat8038** [comment]
Aah man forgot to put it on gitignore will take care next time.

**Comment by Shashwat8038** [comment]
so sorry sir I got excited.I am learning alot from you will take care next
time.

**Pull request closed without merging**
